spring:
  datasource:
    name: mydb
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/guoanjiatest?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  hikari :
    connection-timeout: 60000
    maximum-pool-size: 5
  session:
    store-type: none
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8001

logging:
  file: partnermanager_api.log
  level:
    com:
      guoanfamily: debug

guoanfamily:
  security:
    jwt:
      tokenExpirationTime: 30 # Number of minutes
      refreshTokenExpTime: 120 # Minutes
      tokenIssuer: http://www.guoanfamily.com
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
